zenodo/zenodo-rdm

Dockerfile, docker-compose.full.yml
Docker image build is not *that* slow since the webpack build happens only once.
=> dockerfile: install react-invenio-deposit from github

assets/less/zenodo-rdm/views/card.overrides, assets/less/zenodo-rdm/views/card.variables, templates/semantic-ui/invenio_communities/frontpage.html
Closes https://github.com/zenodo/zenodo-rdm/issues/47
- Commented out the "What is a communities" info section, as we don't have the content yet. To be added.
- When we have the featured communities slideshow, it should be added below the header like this:
=> communities frontpage: edit layout and styling

assets/less/zenodo-rdm/collections/menu.overrides, assets/less/zenodo-rdm/collections/menu.variables, assets/less/zenodo-rdm/elements/button.overrides, assets/less/zenodo-rdm/elements/button.variables, assets/less/zenodo-rdm/elements/segment.overrides, assets/less/zenodo-rdm/elements/segment.variables, assets/less/zenodo-rdm/globals/site.overrides, assets/less/zenodo-rdm/globals/site.variables, templates/semantic-ui/zenodo_rdm/footer.html, templates/semantic-ui/zenodo_rdm/frontpage.html, templates/semantic-ui/zenodo_rdm/header_frontpage.html
closes https://github.com/zenodo/zenodo-rdm/issues/42
- Adds correct color to default button, search button and signup button
- Adds correct height of the top header
- Removes vertical dividers in the footer
- Adds info-boxes to the front page => Styles sidebar boxes on landing page
*Note:* I decreased the brightness of the button colors slightly as they were not good enough for accessibility
=> frontpage: Add information boxes, align styling with Zenodo

docker/nginx/conf.d/default.conf
closes https://github.com/inveniosoftware/helm-invenio/issues/47
Notes:
- file `robots.txt` was [added](https://github.com/inveniosoftware/invenio-app-rdm/commit/cb5bd39104c8a40ef98a18b3b7c42d7da877e08d) in `invenio-app-rdm` and won't be available for this image until the version of `invenio-app-rdm` is upgraded.
=> nginx: added robots.txt rule

assets/less/zenodo-rdm/globals/site.overrides, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/CategoryDropdown.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/FileUploader.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/SupportForm.js, site/zenodo_rdm/templates/semantic-ui/zenodo_rdm/support.html
Closes https://github.com/zenodo/zenodo-rdm/issues/85
=> support form: align styling with prod-zenodo

assets/js/invenio_app_rdm/deposit/override.js
Closes https://github.com/zenodo/zenodo-rdm/issues/46
Overrides `<MetadataAccess />` and metadata-only toggle in `<FileUploaderToolbar />` in the deposit form.
**Needs**
- https://github.com/inveniosoftware/react-invenio-deposit/pull/602
- https://github.com/inveniosoftware/invenio-app-rdm/pull/1970
=> assets: override metadata settings in the deposit form

assets/less/zenodo-rdm/elements/segment.overrides
The placeholder background color is currently white, which does not look great on the gray bg for the sidebar segments in Zenodo. 
This PR aligns the bg color of the placeholder with the sidebar segment.
=> sidebar segment: correct placeholder bg color

templates/semantic-ui/zenodo_rdm/frontpage.html
Closes https://github.com/zenodo/zenodo-rdm/issues/120
=> frontpage: add banner for sandbox info

invenio.cfg
The term `resource_type.subtype` was wrongly mapped.
=> search: fixed resource subtype term mapping

assets/js/invenio_app_rdm/overridableRegistry/mapping.js, invenio.cfg
Closes https://github.com/zenodo/zenodo-rdm/issues/200
This PR removes the overridden `MetadataOnly` components in `mappings.js` and adds the new config variable `RDM_ALLOW_METADATA_ONLY_RECORDS = False` instead.
=> config: remove metadata-only cmp overrides, add config variable instead

site/zenodo_rdm/custom_fields.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1232
Note: this must be spread in two places:
1 - upgrade documentation (e.g. "if you want to have the publishing custom fields grouped together ..."
2 - a place where other instances can have this out of the box (perhaps cookiecutter ?)
=> custom fields: added 'publishing information' fields under one section

site/zenodo_rdm/migrator/streams.yaml
- closes https://github.com/inveniosoftware/invenio-rdm-migrator/issues/75
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/78
=> migrator: disable versioning on records stream

site/zenodo_rdm/migrator/load.py, site/zenodo_rdm/migrator/streams.yaml
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/80
- closes https://github.com/inveniosoftware/invenio-rdm-migrator/issues/79
cleans up the files class, It could potentially be moved to rdm-migrator. But for now just clean up. 
Sample `streams.yaml` to do a run with exising data e.g. for all except last two streams (remember to move previous run csv files to `/tmp`):
```yaml
data_dir: /data
tmp_dir: /tmp
cache_dir: /cache
log_dir: /log
db_uri: postgresql://zenodo:zenodo@localhost:5432/zenodo
users:
existing_data: true
extract:
filepath: /users.jsonl
files:
existing_data: true
communities:
existing_data: true
extract:
filepath: /communities.jsonl
records:
existing_data: true
extract:
filepath: /records.jsonl
drafts:
extract:
filepath: /deposits.jsonl
requests: …
```
=> migrator: re-use existing data loading for zenodo files

app_data/vocabularies/resource_types.yaml
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1316
Applies the changes from https://github.com/inveniosoftware/invenio-rdm-records/pull/1317 to the custom resource types of Zenodo RDM
=> app_data: update resource_type vocabulary

assets/js/components/landing_page/overrides/UpgradeLegacyRecordButton.js, assets/js/invenio_app_rdm/overridableRegistry/mapping.js, templates/semantic-ui/invenio_requests/legacy-record-upgrade/index.html
* override record management component to include upgrade legacy record button
* use community-submission request jinja template for upgrade legacy record request
* closes https://github.com/zenodo/zenodo-rdm/issues/333
Upgrade legacy record button on landing page:
Request in requests list:
Submitted request:
Record tab in open request:
Accepted request:
Declined request:
Declined with a comment:
Declined with another comment:
Expired:
Error handling (also in case if 2 errors occur):
=> requests: add ui for upgrade legacy record request

site/zenodo_rdm/config.py
This is to close https://github.com/inveniosoftware/invenio-app-rdm/issues/2217 and closes https://github.com/zenodo/zenodo-rdm/issues/336.
The redirection for communities/<community>/about doesn't seem to work. We could rely on the redirection from invenio-rdm, instead of having to redefine it in zenodo-rdm
=> Removing obsolete redirection

assets/less/zenodo-rdm/modules/popup.overrides, assets/less/zenodo-rdm/views/item.overrides, invenio.cfg, site/zenodo_rdm/views.py, templates/semantic-ui/zenodo_rdm/frontpage.html, templates/semantic-ui/zenodo_rdm/macros/creators.html, templates/semantic-ui/zenodo_rdm/macros/recent_uploads_list.html, templates/semantic-ui/zenodo_rdm/macros/record_item.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2268
Replaces React "recent uploads"-component on the front page.
=> frontpage: replace react recent uploads component with jinja

migrator/tests/actions/drafts/conftest.py, migrator/tests/actions/drafts/test_draft_actions_stream.py, migrator/tests/actions/users/test_user_actions_stream.py, migrator/zenodo_rdm_migrator/actions/drafts.py, migrator/zenodo_rdm_migrator/actions/users.py
- undo https://github.com/zenodo/zenodo-rdm/commit/637dc4af62857e622b3a2d262795a853051bec86
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/131
Tests passing locally
=> migrator: use microseconds for datetimes instead of str

templates/semantic-ui/zenodo_rdm/frontpage.html
Closes https://github.com/zenodo/rdm-project/issues/210
Removes "Need help?" block from the front page.
=> frontpage: remove need help block

assets/less/zenodo-rdm/elements/list.overrides, assets/less/zenodo-rdm/globals/site.overrides, templates/semantic-ui/zenodo_rdm/footer.html
Closes https://github.com/zenodo/zenodo-rdm/issues/440
- Adds missing links in footer
- Adds semantic HTML for a11y
=> footer: add links and semantic html

invenio.cfg
* closes https://github.com/zenodo/rdm-project/issues/218
Note: current permission logic doesn't allow to create restricted community to anyone: https://github.com/inveniosoftware/invenio-communities/blob/0a1f038cb16063cc03e6ff6b5cb6635dc05a0f0b/invenio_communities/permissions.py#L58
=> communities: don't allow creation of restricted communities

templates/semantic-ui/zenodo_rdm/macros/carousel_item.html
Closes https://github.com/zenodo/rdm-project/issues/233
- Fixes broken link
- Adds more descriptive link text for screen readers
=> carousel: fix broken link

assets/less/zenodo-rdm/elements/label.variables, assets/less/zenodo-rdm/globals/site.variables, assets/less/zenodo-rdm/modules/dropdown.variables, assets/less/zenodo-rdm/modules/popup.overrides, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/CitationsSearch.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/components/CitationRow.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/components/Filter.js, templates/semantic-ui/zenodo_rdm/macros/carousel_item.html, templates/semantic-ui/zenodo_rdm/macros/record_item.html
Closes https://github.com/zenodo/zenodo-rdm/issues/458
Addresses detected a11y issues, including color contrast, see screenshot for updated colors
=> accessibility improvements

site/zenodo_rdm/config.py, site/zenodo_rdm/redirector.py
Partially fixes #482
This PR covers redirect from requests of type
`https://zenodo.org/record/8321034/formats?mimetype=figure.png` -> `https://zenodo.org/records/8321034/media-files/figure.png`
___
The other case with `Accept` header:
```python3
resp = requests.get(
"https://zenodo.org/record/8321034/formats",
headers={"Accept": "application/vnd.taxpub.v1+xml"},
)
```
is not a straightforward fix given the value of `Accept` is equal to the filename. So the only requests that go through are when filename = valid mimetype. If we have a request of type:
```python3
resp = requests.get(
"https://zenodo.org/record/8321034/formats",
headers={"Accept": "figure.png"},
)
```
The application itself doesn't let it go through given `figure.png` is not a valid mimetype. We can probably track it as a …
=> redirection: add legacy formats -> media-files URL redirect

site/zenodo_rdm/generators.py, site/zenodo_rdm/permissions.py
* closes https://github.com/zenodo/rdm-project/issues/242
Enormous copy-paste of permissions has to be changed. Task for this: https://github.com/zenodo/rdm-project/issues/255
=> permissions: override can_manage and everything that depends on it

site/setup.cfg, site/tests/conftest.py, site/tests/requests/test_community_manage_record_request.py, site/zenodo_rdm/legacy/requests/__init__.py, site/zenodo_rdm/legacy/requests/community_manage_record.py, site/zenodo_rdm/legacy/requests/utils.py, templates/semantic-ui/invenio_requests/community-manage-record/user_dashboard.html
* closes https://github.com/zenodo/rdm-project/issues/243
Request details page:
Accepted:
Declined:
Expired:
=> requests: implement a new community manage record request

site/zenodo_rdm/legacy/serializers/__init__.py, site/zenodo_rdm/legacy/serializers/schemas/__init__.py, site/zenodo_rdm/legacy/serializers/schemas/files.py, site/zenodo_rdm/legacy/services.py, templates/semantic-ui/zenodo_rdm/footer.html
Fixes issues with ``/api/deposit/depositions/:id/files``:
1. Endpoint didn't work with a published record - i.e. you could list files only on a draft, not on a published record.
2. Serialisation on above endpoint was broken - service result (obj_list) have "entries" and not "hits".
Sneaked in a menu update as well.
=> legacy: fix legacy files api when published

legacy/zenodo_legacy/funders.py, migrator/scripts/backup_indices.sql, migrator/scripts/dump_affiliations_db.py, migrator/scripts/dump_awards_db.py, migrator/scripts/dump_funders_db.py, migrator/tests/actions/conftest.py, migrator/tests/transform/test_community_transform.py, migrator/tests/transform/test_record_transform.py, migrator/zenodo_rdm_migrator/transform/entries/communities.py, migrator/zenodo_rdm_migrator/transform/entries/parents.py, migrator/zenodo_rdm_migrator/transform/entries/records/custom_fields.py, scripts/admin/community_manage_requests.py, site/tests/legacy/deposits/conftest.py, site/tests/requests/test_community_manage_record_request.py, site/zenodo_rdm/custom_fields.py, site/zenodo_rdm/legacy/deserializers/metadata.py, site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/legacy/requests/community_manage_record.py, site/zenodo_rdm/legacy/serializers/schemas/common.py
- migrator: fix index backup script
- migrator: fix awards dump script
- migrator: add "deletion_status" to community
- legacy/migrator: communities fixes
- legacy/migrator: add "subjects" support
- migrator: update funders dump script
- migrator: add affiliations ROR dump script
=> Legacy and migration fixes

site/zenodo_rdm/legacy/services.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2443
=> legacy: add parent doi link on records only

assets/less/zenodo-rdm/globals/site.overrides
The semi-bold font weight was only intended for the landing page. This PR corrects this mistake.
=> correct font-weight mistake

assets/less/zenodo-rdm/elements/header.overrides, assets/less/zenodo-rdm/elements/list.overrides, assets/less/zenodo-rdm/globals/site.overrides, assets/less/zenodo-rdm/globals/site.variables, templates/semantic-ui/invenio_accounts/login_user.html, templates/semantic-ui/invenio_accounts/register_user.html, templates/semantic-ui/invenio_communities/frontpage.html, templates/semantic-ui/zenodo_rdm/footer.html
Closes https://github.com/zenodo/zenodo-rdm/issues/215
- Fixes sign up page styling
- Aligns footer styling with current Zenodo
- Small a11y fixes for icons and semantic html
=> signup page: improve styling, small a11y fixes overall

site/zenodo_rdm/legacy/serializers/schemas/common.py
* replaces lru_cache with invenio-cache to ensure that cache expiration uses a TTL that is correctly handled
=> communities: replace slug caching with invenio-cache

templates/semantic-ui/zenodo_rdm/records/detail.html
Closes https://github.com/zenodo/rdm-project/issues/384
Hides citations for record preview.
=> landing page: hide citations if preview

site/zenodo_rdm/sitemap/tasks.py, site/zenodo_rdm/sitemap/views.py
Fixes https://github.com/zenodo/rdm-project/issues/559
After deploying this change, please run:
```python3
from zenodo_rdm.sitemap.tasks import update_sitemap_cache
update_sitemap_cache()
```
=> sitemap: store only urls to cache

site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/FileUploader.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/SupportForm.js
Closes https://github.com/zenodo/rdm-project/issues/531
=> support form: add support for pdf files

templates/semantic-ui/zenodo_rdm/records/detail.html
* closes https://github.com/zenodo/rdm-project/issues/471
In case of no files (all the files are in pending/failed state):
=> record details: change handling of no files in the record

templates/semantic-ui/zenodo_rdm/records/detail.html
* Fixes an issue with citations not rendering for external DOIs because the record doesn't have a parent record pid.
Closes zenodo/rdm-project#607
=> records: fix citations not showing for ext DOIs

assets/less/zenodo-rdm/globals/site.overrides, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/BlrSearch.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/api/config.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/components/BlrResultsLoader.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/components/Filter.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/components/LayoutSwitchButtons.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/components/NoResults.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/components/RecordItem.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/components/ResultsLayout.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/index.js, site/zenodo_rdm/filters.py, site/zenodo_rdm/views.py, site/zenodo_rdm/webpack.py, templates/semantic-ui/zenodo_rdm/records/detail.html
Closes https://github.com/zenodo/rdm-project/issues/567
Needs https://github.com/inveniosoftware/react-searchkit/pull/260
**Edit:** After discussing with Lars, it was decided to remove the search bar for now, as there are issues related to having the initial query string (to show only related results for the specific record) + additional query strings added by the user. In order to add the search bar back, these are the known alternatives that will need a solution:
- if the query string is added to the state (`queryString`), the string shows up in the input field. The input field should be empty, but the query string needs to remain.
- if the query string is added directly to the endpoint url parameters, the search does not work, as there will be two `q` parameters once another search is …
=> landing page: add blr related works section

Pipfile, Pipfile.lock, site/zenodo_rdm/custom_fields.py, site/zenodo_rdm/custom_fields/__init__.py, site/zenodo_rdm/custom_fields/domain_fields.py, site/zenodo_rdm/custom_fields/legacy.py, site/zenodo_rdm/custom_fields/publishing.py, site/zenodo_rdm/legacy/serializers/schemas/legacyjson.py
* Closes Issue [#632](https://github.com/zenodo/rdm-project/issues/632)
*closes https://github.com/zenodo/rdm-project/issues/649
=> custom_fields: enabling visibility on deposit form

invenio.cfg, site/zenodo_rdm/queryparser.py
Fixes searchers such as:
```
doi:10.5281/zenodo.12345
communities:biosyslit
user:176
```
Depends on https://github.com/inveniosoftware/invenio-records-resources/pull/557
=> queryparser: fix doi and communities field search

static/robots.txt
closes https://github.com/zenodo/ops/issues/358
* added rule to allow crawling of /api/files
=> global: updated robots.txt

invenio.cfg, site/zenodo_rdm/files.py
closes https://github.com/zenodo/ops/issues/322
I added [docs](https://digital-repositories.web.cern.ch/zenodo/support/operations/#eos-x509-certificate-replacement) on how to replace the certificate.
This was tested in `zenodo-rdm-qa`, inside a pod. I added the configmap to the `worker` deployment and mounted the certificates. The test was run in an `invenio shell`, using a `requests.Session.get` request to retrieve a file from eosmedia and it worked.
⚠️ even though the changes are behind a configuration, please align with me before this is deployed
In Openshift, set the following variables (we need to create the deployment config first `INVENIO_ZENODO_EOS_*` so they are added to the application):
```python
INVENIO_ZENODO_EOS_OFFLOAD_AUTH_X509 = True …
```
=> files: added x509 authentication to EOS offload.

templates/semantic-ui/zenodo_rdm/macros/communities_list.html, templates/semantic-ui/zenodo_rdm/macros/record_item.html
Needs: https://github.com/zenodo/zenodo-rdm/issues/698
* closes https://github.com/zenodo/zenodo-rdm/issues/715
Preview:
Also used in frontpage:
=> record preview: display communities list

templates/semantic-ui/zenodo_rdm/macros/record_item.html, templates/themes/horizon/invenio_communities/details/home/index.html
Closes Issue [#719](https://github.com/zenodo/zenodo-rdm/issues/719)
- frontpage: label colouring should follow the EC theme
=> recent uploads: updated label colors and styling

templates/themes/horizon/invenio_app_rdm/site_footer.html
Added site_footer for customization specific to Zenodo https://github.com/inveniosoftware/invenio-app-rdm/pull/2578#discussion_r1494826801
- powered by InvenioRDM -> powered by CERN Data Center (current zenodo one)
=> footer: added themed site_footer

site/zenodo_rdm/openaire/serializers/__init__.py, site/zenodo_rdm/openaire/serializers/schema.py
closes https://github.com/zenodo/ops/issues/313
=> openaire: added award title and acronym to serialization.

templates/semantic-ui/zenodo_rdm/macros/communities_list.html, templates/semantic-ui/zenodo_rdm/macros/record_item.html, templates/themes/horizon/invenio_communities/details/home/index.html
* closes https://github.com/zenodo/zenodo-rdm/issues/716
Also moved "Part of" to the small bottom information
Frontpage:
Don't highlight community logo in the community front page:
=> frontpage: display verified community logo

scripts/ec_transfer_records.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1677
=> scripts: added script to move records and communities in bulk.

templates/themes/horizon/invenio_app_rdm/footer.html, templates/themes/horizon/invenio_communities/details/header.html, templates/themes/horizon/invenio_communities/details/home/index.html
Fixes #786
* The logo is now also linking to the community (not only the text next to the logo).
* Modified the text related to the EU (and add a missing "the").
=>  Frontpage: header logo link and footer text change

templates/themes/horizon/invenio_communities/details/home/index.html
Fixes #785 
* [Before](https://ptamarit.web.cern.ch/temp/zenodo-rdm-785-before.html)
* [After](https://ptamarit.web.cern.ch/temp/zenodo-rdm-785-after.html)
=> frontpage: fix grid layout responsiveness

site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/SupportForm.js
* Adding an `errorMessage` state.
* Setting `errorMessage` to `null` when the submit starts
* Setting `errorMessage` to the error message in case of error.
* Showing a generic error message below the submit button if `errorMessage` is not null.
=> support form: show message in case of submit error

site/zenodo_rdm/support/support.py
We have this exception on Sentry:
```
TypeError
can only concatenate str (not "NoneType") to str
```
It seems that the browser version can be `None`:
```
{browser: 'Other', browser_version: None, device: 'Other', os: 'Other'}
```
=> support: added default strings for browser information

assets/less/zenodo-rdm/modules/popup.overrides
Close https://github.com/zenodo/ops/issues/341
Problem:
After: 
And preserves how it looks with wide viewports
=> ui: prevent checksum popup overflowing on mobile

Pipfile.lock, invenio.cfg
Removed facet `is_published` for now to deploy a small security fix. 
facet was added in https://github.com/zenodo/zenodo-rdm/pull/807 , we need to add it later on. I will create a separate PR
=> installation: bump dependencies

invenio.cfg
The removed lines from `invenio.cfg` in this commit are the same as and override the lines in https://github.com/zenodo/zenodo-rdm/blob/43c4d5995417cda205d65d21671dc24c12920240/site/zenodo_rdm/openaire/config.py. @slint has already prevented this change affecting prod
related to https://github.com/inveniosoftware/invenio-rdm-records/pull/1699#issuecomment-2017771501
=> config: remove duplicate code from invenio.cfg

app_data/vocabularies/licenses.csv
Running `invenio-cli services setup --force` fails on line 38 (a line with double quotes) in the new CSV dialect sniffing logic added in https://github.com/inveniosoftware/invenio-rdm-records/pull/1721.
Also, going to https://github.com/zenodo/zenodo-rdm/blob/master/app_data/vocabularies/licenses.csv, GitHub shows:
> We can make this file beautiful and searchable if this error is corrected: Illegal quoting in line 38.
Instead of just fixing the problem on this line, I converted the file to use comma delimiters as done in https://github.com/inveniosoftware/invenio-rdm-records/pull/1721.
I used the following snippet:
```python
import csv
with open(r"licenses.csv") as in_file, open(r"licenses-out.csv", 'w') as out_file:
semicolonin = csv.reader(in_file, delimiter=';')
commaout = …
```
=> fix: csv: change delimiter to comma to pass CSV dialect sniffing

site/zenodo_rdm/permissions.py
Currently, admins can't modify files due to a bug with permissions.
=> permissions: fixed files modification permissions for external DOIs

site/zenodo_rdm/previewer/mirador.py
- Allows annotations to be loaded from .wadm files instead of .short.wadm
Related to: https://github.com/zenodo/zenodo-rdm/issues/876
=> mirador: updated annotation files ext

invenio.cfg, site/zenodo_rdm/previewer/mirador.py
Closes Issue: https://github.com/zenodo/zenodo-rdm/issues/894
=> mirador: set default sidebar state to closed

invenio.cfg, site/tests/openaire/test_components.py, site/tests/openaire/test_tasks.py, site/zenodo_rdm/openaire/tasks.py, site/zenodo_rdm/subcommunities/schema.py
Request to retry failures is malformed, the `originalID` is expected as a string parameter and not in the request body
1. fixed request to delete from openaire
2. when retrying records, fixed record resolving for deleted records
3. moved `execute_moderation_actions` task to low priority queue
=> openaire: fixed delete task

scripts/deploy.py
Since we added a new deployment, we have to update its version when we release. 
If we move the scheduler to a container inside the existing beat, we don't need this PR.
=> scripts: added custom worker beat to deployments.

site/zenodo_rdm/config.py, templates/semantic-ui/invenio_app_rdm/records/macros/files.html, templates/semantic-ui/zenodo_rdm/records/detail.html
Closes Issue https://github.com/zenodo/ops/issues/476
- If a file has a filename in metadata.preview and that file is present in files
- Then it previews that file otherwise default to the current file on initial preview
- Also generates links for preview button based on that
- Added annotate button for redirection to annostar instance for specific communities
- The files right now have been uploaded with access hidden in the screenshot below for the specific usecase
=> preview: updated pdf redirect based on metadata

invenio.cfg
closes https://github.com/zenodo/zenodo-rdm/issues/937
depends on https://github.com/zenodo/zenodo-rdm/pull/940
=> config: added swh cleanup task to beat

Dockerfile
* The `requests-kerberos` and `invenio-xrootd` modules require compiling
and building wheels for their dependencies that can take some time.
* Installing the packages before installing all of the other application
dependencies can save us a couple of minutes and better separate
"system" and "application" packages.
=> docker: improve layer caching for xrootd and kerberos Python deps

site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/BlrSearch.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/components/LayoutSwitchButtons.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/blr-related-works/components/ResultsLayout.js
Layout for Linked Records
- Defaults to grid view
- Updated grid and list layout for number of records to display
=> landing page: updated linked records layout

site/setup.cfg, site/zenodo_rdm/index_templates/__init__.py, site/zenodo_rdm/index_templates/os-v2/__init__.py, site/zenodo_rdm/index_templates/os-v2/rdmrecords-template.json
This is to make sure that records and drafts indices are created with 3 shards.
=> index_templates: configure number of shards for record indices

site/tests/openaire/test_components.py, site/tests/openaire/test_tasks.py, site/zenodo_rdm/openaire/config.py, site/zenodo_rdm/openaire/tasks.py, site/zenodo_rdm/openaire/utils.py
* Switches to the alternative "/api/result/{openaire_id}" OpenAIRE endpoint, which can be used when only knowing the DOI of a record.
* Adjust task retry time window to 10min since maximum time is 15min.
* Instead of failling completely, only log failed requests to OpenAIRE beta instance.
* Closes #1022.
=> openaire: fix direct index deletion calls

site/tests/requests/test_community_manage_record_request.py, site/zenodo_rdm/legacy/requests/community_manage_record.py
Before and after
Perhaps title could be changed to something like "Allow communities to manage your pre-migration records"
=> requests: improve community manage record message

site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/horizon/index.js, templates/themes/horizon/invenio_communities/details/home/index.html
Partially closes inveniosoftware/invenio-communities#1227
Depends on inveniosoftware/invenio-rdm-records#1848
The "Search in all communities" input in the community front page is currently auto-focused (see linked issue).
While it makes sense for the auto-focus to be present in a model, it does not in a community front page where this is not the only input and it is lower in the page.
=>  horizon: frontpage: disable autofocus on CommunitySelectionSearch & bring back projects to frontpage

site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/horizon/index.js, templates/themes/horizon/invenio_communities/details/home/index.html
Partially fixes inveniosoftware/invenio-communities#1227
Depends on inveniosoftware/invenio-rdm-records#1850
Now that the `CommunitySelectionSearch` is used in the community front page (see linked issue), there might not be an authenticated user and the myCommunities tab might not make sense.
Here we are disabled `myCommunities` if the user is not authenticated.
=> horizon: frontpage: disable My communities for unauthenticated users on CommunitySelectionSearch

Pipfile, Pipfile.lock
📁 invenio-accounts (5.1.4 -> 5.1.5 🐛)
release: v5.1.5
model: make forward compatible to sqlalchemy >= 2
📁 invenio-admin (1.4.0 -> 1.4.1 🐛)
📦 release: v1.4.1
docs: fix intersphinx config
setup: pin wtforms
3.2.0 makes a breaking change https://wtforms.readthedocs.io/en/3.2.x/changes/
📁 invenio-banners (3.1.1 -> 3.2.0 🌈)
release: v3.2.0
feat(tests): add test for html banner message
feat(administration): use html editor for message
global: use uow instead of explicit commit
refactor: use session.get where possible
* recomended sqlalchemy syntax for sqlalchemy >= 2.0 fix: tests
* test_banner_creation uses the active banner. the service method which is tested validates the data over the schema where start_datetime and end_datetime is a required field and it has to look like: '%Y-%m-%d …
=> installation: bump dependencies (pin wtforms = "<3.0.0")

scripts/deploy.py, site/zenodo_rdm/cli.py, site/zenodo_rdm/moderation/handlers.py
- **scripts: reorder services/containers in deployment**
- **moderation: fix CLI usage for importing link domains**
- **moderation: handle system actions for the community flow**
=> Moderation-related fixes

Pipfile, Pipfile.lock, docker-compose.full.yml, docker-compose.yml, docker-services.yml, scripts/run_script.py, site/zenodo_rdm/legacy/services.py
- **scripts: fix hashbang for "run_script.py"**
- **docker: remove obsolete "version" field**
- **config: fix parent DOI link**
=> Bump deps and various fixes

Pipfile, invenio.cfg, site/zenodo_rdm/api.py, site/zenodo_rdm/config.py, site/zenodo_rdm/legacy/serializers/schemas/zenodojson.py, site/zenodo_rdm/schema.py, site/zenodo_rdm/serializers/__init__.py, site/zenodo_rdm/serializers/bibtex.py, site/zenodo_rdm/serializers/cff.py, site/zenodo_rdm/serializers/codemeta.py, site/zenodo_rdm/serializers/datacite.py
closes https://github.com/zenodo/zenodo-rdm/issues/936
=> record: added swh field and serializers

Pipfile, Pipfile.lock, invenio.cfg, scripts/sleep.py, site/zenodo_rdm/config.py, site/zenodo_rdm/legacy/requests/utils.py, site/zenodo_rdm/subcommunities/__init__.py, site/zenodo_rdm/subcommunities/request.py
=> subcommunities: add invitation request

site/setup.cfg, site/zenodo_rdm/curation/jobs.py
Closes https://github.com/zenodo/ops/issues/506
=> curation: add EURecordCuration job

Pipfile.lock, site/zenodo_rdm/github/release.py
Co-authored-by: Manuel Costa <manuel.alejandro.de.oliveira.da.costa@cern.ch>
=> github: handle missing repo license

site/zenodo_rdm/github/release.py
`legacy_to_rdm` contains deprecated licenses (i.e. `GPL-3.0`) that is needed before publishing the record.
=> github: transform gh license to RDM

Pipfile, Pipfile.lock, site/zenodo_rdm/subcommunities/request.py
- **subcommunities: use scan to fetch all records of community**
* Fixes a bug where only the first 25 records of a community were added
when the subcommunity request was accepted.
📁 invenio-communities (17.6.0 -> 17.7.0 🌈)
📦 release: v17.7.0
service: allow passing custom expires_at
📦 release: v17.6.1
mappings: add `identifiers` to parent organizations
* Adds the missing `identifiers` property to parent communities.
📁 invenio-github (1.5.3 -> 1.5.4 🐛)
release: v1.5.4
fix: publish with translations
📁 invenio-rdm-records (16.4.0 -> 16.4.1 🐛)
📦 release: v16.4.1
mappings: add missing `identifiers` to community orgs
* Adds the missing `identifiers` mapping field to community
organizations.
📁 invenio-users-resources (6.1.1 -> 6.1.3 🐛)
📦 release: v6.1.3 …
=> Fix communuity records listing and bump dependencies

assets/less/zenodo-rdm/globals/site.overrides
This change has been implemented in invenio-app-rdm: see inveniosoftware/invenio-app-rdm#2961
=> globals: site.overrides: remove custom PDF preview iframe height

site/zenodo_rdm/legacy/services.py
* We need to explicitly mention additional parameters like "size" when
using the `RecordEndpointLink`.
=> legacy: fix thumb250 link generation

site/tests/openaire/test_openaire_helpers.py, site/zenodo_rdm/openaire/utils.py
* We can now use the much simpler `/search/result?pid=...` endpoint,
which works independent of the record's resource type.
=> openaire: fix OpenAIRE EXPLORE link generation

invenio.cfg, pyproject.toml, site/tests/conftest.py, site/zenodo_rdm/communities_ui/views/communities.py, site/zenodo_rdm/exporter/tasks.py, site/zenodo_rdm/legacy/resources.py, site/zenodo_rdm/permissions.py, site/zenodo_rdm/providers.py, site/zenodo_rdm/resources.py, uv.lock
- **fix(serializers): use Zenodo DataCite and BibTex serializers consistently**
Our custom Zenodo DataCite and BibTex serializers that contain the `swh`
field, were only used in the record landing page export format
serializers. This is an issue since we want that REST API and results
and DataCite DOI registration to actually use them as well.
This change moves the serializer definitions for REST APIs in a separate
file, since having them under the legacy namespace didn't make sense.
- **installation: bump invenio-swh**
📁 invenio-swh (0.13.3 -> 0.13.4 🐛)
📦 release: v0.13.4
fix(systemfields): use correct variable for loading SWHDeposit
- **chore: formatting and remove unused imports**
=> Fix SWH and DataCite/BibTex serialization
