Pipfile, Pipfile.lock, assets/less/site/globals/site.variables, assets/less/theme.config, assets/less/zenodo-rdm/globals/site.overrides, assets/less/zenodo-rdm/globals/site.variables, invenio.cfg
Things seem to work in v10.dev12. Just some minor css issues:
We might want to fine tune configuration.
=> WIP: global: upgrade to app rdm v10

assets/less/zenodo-rdm/elements/segment.overrides
Closes https://github.com/zenodo/zenodo-rdm/issues/45
- Note that this screenshot includes the styling from https://github.com/zenodo/zenodo-rdm/pull/54
=> theme: style record details page

static/describo/zenodo-describo-profile.json
closes https://github.com/zenodo/zenodo-rdm/issues/56
=> profile: added describo profile.

assets/less/zenodo-rdm/elements/button.overrides, invenio.cfg, templates/semantic-ui/invenio_communities/frontpage.html, templates/semantic-ui/zenodo_rdm/frontpage.html
Closes https://github.com/zenodo/zenodo-rdm/issues/66
Needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1946
and https://github.com/inveniosoftware/invenio-communities/pull/822
=> frontpage: align with new rdm-template

app_data/vocabularies.yaml, app_data/vocabularies/resource_types.yaml
=> fixtures: update resource types

invenio.cfg
=> config: add custom fields

assets/less/zenodo-rdm/globals/site.overrides, assets/less/zenodo-rdm/globals/site.variables
=> Footer: revert color white

invenio.cfg
Closes https://github.com/zenodo/zenodo-rdm/issues/43
- Adds subjects to search facets
=> config: add subjects to facets

site/zenodo_rdm/migrator/README.md, site/zenodo_rdm/migrator/transform.py
=> docs: how to carry out a test migration to paas instance

app_data/oai_sets.yaml
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1931
=> add custom oai sets

assets/less/zenodo-rdm/globals/site.overrides, templates/semantic-ui/invenio_accounts/register_user.html
=> signup: added orcid and github signup buttons

assets/less/zenodo-rdm/collections/table.overrides, assets/less/zenodo-rdm/collections/table.variables, assets/less/zenodo-rdm/elements/list.overrides, invenio.cfg, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/CitationsSearch.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/api/config.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/components/CitationRow.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/components/ErrorMessage.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/components/Filter.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/components/NoCitations.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/components/Results.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/index.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/sanitizer.js, site/zenodo_rdm/config.py, site/zenodo_rdm/webpack.py, templates/semantic-ui/invenio_app_rdm/records/detail.html
Closes https://github.com/zenodo/rdm-project/issues/26
=> landing page: add citations search box

Pipfile.lock, invenio.cfg, templates/semantic-ui/zenodo_rdm/records/detail.html
* update pipfile.lock
* closes https://github.com/zenodo/zenodo-rdm/issues/126
=> records_ui: add file migration message

site/setup.cfg, site/zenodo_rdm/cli.py
addresses https://github.com/inveniosoftware/invenio-records-permissions/issues/88
=> zenodo-rdm: add cli command to delete records

site/zenodo_rdm/config.py
closes https://github.com/zenodo/zenodo-rdm/issues/104
=> migration: added redirection rules

assets/less/zenodo-rdm/collections/table.overrides, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/CitationsSearch.js
Closes https://github.com/zenodo/zenodo-rdm/issues/140
=> citations: add border to top and bottom of table

site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/CitationsSearch.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1999
=> citations: disable url manipulation

templates/semantic-ui/zenodo_rdm/records/detail.html
Closes https://github.com/zenodo/zenodo-rdm/issues/155
=> landing page: add link to original record

invenio.cfg
=> search: added legacy search map

docker-compose.full.yml
closes https://github.com/zenodo/zenodo-rdm/issues/166
=> pgadmin: added container to docker-compose.full.yml

invenio.cfg, scripts/zenodo_old_rest_api_flow.py, site/setup.cfg, site/tests/conftest.py, site/zenodo_rdm/legacy/__init__.py, site/zenodo_rdm/legacy/deserializers/__init__.py, site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/legacy/ext.py, site/zenodo_rdm/legacy/resources.py, site/zenodo_rdm/legacy/serializers/__init__.py, site/zenodo_rdm/legacy/serializers/schemas.py, site/zenodo_rdm/legacy/services.py, site/zenodo_rdm/legacy/views.py
- legacy: initial quickstart flow implementation
- closes #99.
Depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/1139.
=> Legacy REST API

invenio.cfg
Undo when https://github.com/inveniosoftware/invenio-oauthclient/pull/297/files is merged and released
=> config: update aai oauth client to use keycloak

invenio.cfg
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1191
- Added `Journal` custom field to zenodo RDM
=> contrib: added journal custom field.

invenio.cfg
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1211
**REQUIRES**
- https://github.com/inveniosoftware/react-invenio-forms/pull/192
- https://github.com/inveniosoftware/invenio-app-rdm/pull/2102
=> contrib: added meeting custom field

invenio.cfg
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1215
=> contrib: added imprint custom field

invenio.cfg
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1217
=> contrib: added notes custom field

invenio.cfg
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1219
=> contrib: added thesis custom field

invenio.cfg
- closes https://github.com/inveniosoftware/invenio-oauthclient/issues/296
=> oauthclient: enable scopes configuration for keycloak

invenio.cfg, site/zenodo_rdm/config.py, site/zenodo_rdm/custom_fields.py, site/zenodo_rdm/redirector.py
I'm sorry, I could not help myself. In the comments I will leave extra things that should be refactored.
It is failing in isort/pydocstyle, I will fixed if the changes are agreed upon.
=> config cleanup

site/tests/migrator/transform/test_record_transform.py, site/zenodo_rdm/migrator/transform/records/__init__.py, site/zenodo_rdm/migrator/transform/records/metadata.py, site/zenodo_rdm/migrator/transform/records/records.py
- includes #224 **review only the last commit**
- closes https://github.com/zenodo/zenodo-rdm/issues/231
=> Migrator contributors

invenio.cfg, site/zenodo_rdm/custom_fields.py
closes https://github.com/zenodo/zenodo-rdm/issues/254
=> custom fields: added codemeta.

site/tests/migrator/transform/test_community_transform.py, site/tests/migrator/transform/test_record_transform.py, site/zenodo_rdm/migrator/transform/records/records.py
closes https://github.com/zenodo/zenodo-rdm/issues/229
=> migrator: added multiple communities.

site/tests/migrator/transform/test_featured_community_transform.py, site/zenodo_rdm/migrator/extract.py, site/zenodo_rdm/migrator/stream.py, site/zenodo_rdm/migrator/transform/communities.py, site/zenodo_rdm/migrator/transform/entries/__init__.py, site/zenodo_rdm/migrator/transform/entries/communities.py
closes https://github.com/zenodo/zenodo-rdm/issues/258
=> migrator: added featured communities

site/tests/migrator/transform/test_record_transform.py, site/zenodo_rdm/migrator/transform/communities.py, site/zenodo_rdm/migrator/transform/entries/records/metadata.py
=> WIP: added missing fields.

site/zenodo_rdm/migrator/README.md, site/zenodo_rdm/migrator/extract.py
- migrator: add and fix extract SQL queries
- migrator: document how to generate dumps
=> Query fixes and dump docs

invenio.cfg, site/zenodo_rdm/migrator/extract.py, site/zenodo_rdm/migrator/transform/entries/records/custom_fields.py, site/zenodo_rdm/migrator/transform/entries/records/metadata.py, site/zenodo_rdm/migrator/transform/entries/records/records.py, site/zenodo_rdm/migrator/transform/records.py
- closes https://github.com/zenodo/zenodo-rdm/issues/241
=> drafts and versions

invenio.cfg, site/zenodo_rdm/migrator/transform/entries/records/metadata.py, site/zenodo_rdm/migrator/transform/records.py
Tested record with `dates` and they were succesfully migrated and render in the UI.
=> migrator: added dates record.

migrate.sh
**DISCLAIMER** : not meant to be run, instead it has steps as guidelines.
=> migration: added basic script with instructions

migrate.sh, site/tests/migrator/transform/test_record_transform.py, site/zenodo_rdm/migrator/transform/entries/records/metadata.py, wipe_recreate.sh
closes #262 
This PR fixes minor issues and adds tests for `metadata` fields.
=> migrator: added metadata locations for records.

migrate.sh, site/MANIFEST.in, site/zenodo_rdm/migrator/README.md, site/zenodo_rdm/migrator/__main__.py, site/zenodo_rdm/migrator/scripts/backup_indices.sql, site/zenodo_rdm/migrator/scripts/drop_indices.sql, site/zenodo_rdm/migrator/scripts/gen_create_constraints.sql, site/zenodo_rdm/migrator/scripts/gen_delete_constraints.sql, site/zenodo_rdm/migrator/scripts/restore_indices.sql, site/zenodo_rdm/migrator/scripts/update_sequences.sql, site/zenodo_rdm/migrator/stream.py, site/zenodo_rdm/migrator/streams.yaml, site/zenodo_rdm/migrator/transform/entries/records/metadata.py, site/zenodo_rdm/migrator/transform/records.py
- migrator: files stream fixes and integration
- migrator: drafts transformer fixes
- migrator: update migrate steps
- migrator: constraint and index loading scripts
- migrator: handle missing conceptrecid for drafts
=> Files stream, constraints/indices recreation, and minor fixes

site/zenodo_rdm/migrator/load.py, site/zenodo_rdm/migrator/stream.py, site/zenodo_rdm/migrator/streams.yaml
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/64
- closes https://github.com/inveniosoftware/invenio-rdm-migrator/issues/61
=> migrator: deduplicate tmp_dir path

site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/legacy/serializers/schemas.py
- closes #265 
Created a desposit using legacy API, see request and response:
The same deposit is displayable in the web interface (i.e. RDM API)
=> legacy api: de/serializer for funding field

site/tests/migrator/transform/test_record_transform.py, site/zenodo_rdm/migrator/transform/entries/records/metadata.py
closes https://github.com/zenodo/zenodo-rdm/issues/313
=> migrator: added funding record metadata

site/zenodo_rdm/migrator/README.md, site/zenodo_rdm/migrator/extract.py
Addresses https://github.com/zenodo/zenodo-rdm/issues/312.
=> migrator: add community logs to extract query

Pipfile.lock, site/zenodo_rdm/migrator/transform/communities.py, site/zenodo_rdm/migrator/transform/entries/communities.py
closes https://github.com/zenodo/zenodo-rdm/issues/312
=> migrator: added community files

site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/legacy/serializers/schemas.py, site/zenodo_rdm/legacy/services.py, site/zenodo_rdm/legacy/vocabularies/licenses.py, site/zenodo_rdm/legacy/vocabularies/utils.py
closes https://github.com/zenodo/zenodo-rdm/issues/187
=> legacy: added missing fields 

site/tests/migrator/transform/test_record_transform.py, site/zenodo_rdm/migrator/errors.py, site/zenodo_rdm/migrator/transform/entries/records/metadata.py
- closes https://github.com/zenodo/zenodo-rdm/issues/348
=> migrator, transform: ensure validation of identifiers

invenio.cfg, site/tests/conftest.py, site/tests/test_record_file_permissions.py, site/zenodo_rdm/generators.py, site/zenodo_rdm/permissions.py
* manage permissions depending on a new permission flag
* closes https://github.com/zenodo/zenodo-rdm/issues/271
=> permissions: override RDM permission policy

invenio.cfg, site/tests/conftest.py, site/tests/legacy/conftest.py, site/tests/legacy/test_communities.py, site/tests/legacy/test_deposit_api.py, site/tests/legacy/test_quickstart.py, site/zenodo_rdm/custom_fields.py, site/zenodo_rdm/legacy/deserializers/metadata.py, site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/legacy/serializers/schemas.py, site/zenodo_rdm/legacy/services.py
Closes #346.
- tests: minor fixes and quickstart flow
- legacy: add communities field
=> legacy: communities field

Pipfile.lock, site/setup.cfg, site/tests/conftest.py, site/tests/requests/conftest.py, site/tests/requests/test_record_upgrade_request.py, site/tests/resources/test_record_file_permissions.py, site/zenodo_rdm/legacy/requests/__init__.py, site/zenodo_rdm/legacy/requests/record_upgrade.py, site/zenodo_rdm/legacy/requests/utils.py
* add submit, accept, decline and expire actions logic
* closes https://github.com/zenodo/zenodo-rdm/issues/284
The description of a request preview:
=> requests: add a legacy record upgrade request

Pipfile.lock, site/zenodo_rdm/custom_fields.py, site/zenodo_rdm/templates/semantic-ui/zenodo_rdm/obo.html
closes https://github.com/zenodo/zenodo-rdm/issues/264
requires https://github.com/inveniosoftware/invenio-app-rdm/pull/2244
=> custom-fields: add landing page only zenodo custom fields

migrate.sh, site/MANIFEST.in, site/zenodo_rdm/migrator/scripts/add_admins.sh
- closes https://github.com/zenodo/zenodo-rdm/issues/342
=> migration: add admins script

Pipfile.lock, site/tests/migrator/transform/test_record_transform.py, site/zenodo_rdm/migrator/extract.py, site/zenodo_rdm/migrator/transform/entries/records/record_files.py, site/zenodo_rdm/migrator/transform/entries/records/records.py, site/zenodo_rdm/migrator/transform/records.py
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/89
- closes https://github.com/zenodo/zenodo-rdm/issues/311
=> Draft files

site/tests/__init__.py, site/tests/conftest.py, site/tests/fake_datacite_client.py, site/tests/legacy/deposits/conftest.py, site/tests/legacy/deposits/test_rest_api_metadata.py, site/tests/legacy/deposits/test_rest_api_simpleflow.py, site/zenodo_rdm/legacy/deserializers/metadata.py, site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/legacy/resources.py, site/zenodo_rdm/legacy/serializers/schemas.py, site/zenodo_rdm/legacy/services.py
closes https://github.com/zenodo/zenodo-rdm/issues/385
=> legacy: port rest api tests

site/setup.cfg, site/tests/legacy/deposits/conftest.py, site/tests/legacy/test_stubs.py, site/zenodo_rdm/legacy/views.py
=> legacy: add extra formats stub endpoints

Pipfile.lock, site/zenodo_rdm/migrator/__main__.py, site/zenodo_rdm/migrator/extract.py, site/zenodo_rdm/migrator/load.py, site/zenodo_rdm/migrator/stream.py, site/zenodo_rdm/migrator/streams.yaml
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/105 released and updating `Pipfile.lock`
- closes https://github.com/zenodo/zenodo-rdm/issues/246
=> migrator: generalize existing data file loading

assets/less/zenodo-rdm/modules/transition.overrides, assets/less/zenodo-rdm/modules/transition.variables, invenio.cfg, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/communities-carousel.js, site/zenodo_rdm/views.py, site/zenodo_rdm/webpack.py, templates/semantic-ui/zenodo_rdm/frontpage.html, templates/semantic-ui/zenodo_rdm/macros/carousel_item.html, templates/semantic-ui/zenodo_rdm/macros/communities_carousel_slides.html, templates/semantic-ui/zenodo_rdm/macros/creators.html, templates/semantic-ui/zenodo_rdm/macros/featured_communities_carousel.html, templates/semantic-ui/zenodo_rdm/macros/record_item.html
Closes https://github.com/inveniosoftware/invenio-communities/issues/874
Adds vanilla js version of the community carousel.
**Requirements:**
- https://github.com/inveniosoftware/invenio-app-rdm/pull/2243
https://github.com/zenodo/zenodo-rdm/assets/21052053/a7452d9c-2263-47fa-b5f1-a2ca2b1829b0
=> frontpage: add vanilla js version of communities carousel

assets/less/zenodo-rdm/elements/segment.overrides, assets/less/zenodo-rdm/elements/segment.variables, assets/less/zenodo-rdm/globals/site.overrides, assets/less/zenodo-rdm/views/item.overrides, templates/semantic-ui/zenodo_rdm/frontpage.html
Closes https://github.com/zenodo/zenodo-rdm/issues/405
Needs PR https://github.com/inveniosoftware/invenio-app-rdm/pull/2293
Mobile:
Tablet:
Desktop:
Tablet/mobile:
Desktop:
=> segment: adjust styling for sidebar containers

Pipfile.lock
* github API csrf fix
* github UI style improvements
=> setup: bump invenio dependencies

site/zenodo_rdm/custom_fields.py
Addresses https://github.com/zenodo/rdm-project/issues/170
=> Showing the software fields on the upload page

migrator/setup.cfg, migrator/tests/actions/drafts/test_drafts_actions.py, migrator/tests/actions/users/test_user_actions.py, migrator/zenodo_rdm_migrator/actions/__init__.py, migrator/zenodo_rdm_migrator/actions/transform/__init__.py, migrator/zenodo_rdm_migrator/actions/transform/drafts.py, migrator/zenodo_rdm_migrator/actions/transform/users.py, migrator/zenodo_rdm_migrator/transform/transactions.py
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/132
=> migrator: namespace load and transform actions

migrator/setup.cfg, migrator/zenodo_rdm_migrator/extract/kafka.py
- migrator: move dictdiffer to install requires
- migrator: flexible Kafka offset start
=> migrator: deps fix and Kafka offset param

migrator/zenodo_rdm_migrator/actions/transform/drafts.py, migrator/zenodo_rdm_migrator/transform/entries/records/records.py
- requires https://github.com/inveniosoftware/invenio-rdm-migrator/pull/138
=> migrator: split create draft action data class entities

Pipfile.lock, assets/js/components/landing_page/overrides/FileUploaderNewVersion.js, assets/js/components/landing_page/overrides/UpgradeLegacyRecordButton.js, assets/js/invenio_app_rdm/overridableRegistry/mapping.js, site/setup.cfg, site/zenodo_rdm/config.py, site/zenodo_rdm/generators.py, site/zenodo_rdm/permissions.py
* permissions: add custom permissions to upload media files
* closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2259
* closes: https://github.com/zenodo/zenodo-rdm/issues/423
New draft, based on managed/unmanaged DOI:
Published files edition:
=> service: unlock files for external dois - disable record versioning

Pipfile.lock, invenio.cfg, legacy/setup.cfg, migrator/setup.cfg, site/setup.cfg, site/zenodo_rdm/profiler.py, site/zenodo_rdm/templates/semantic-ui/profiler/index.html
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2361
https://github.com/inveniosoftware/invenio-app-rdm/assets/1814661/85982f58-f4d8-4f95-a8d6-997773eb48e9
=> profiler: initial module

Pipfile.lock, invenio.cfg, site/setup.cfg, site/tests/conftest.py, site/tests/legacy/deposits/test_rest_api_metadata.py, site/tests/legacy/deposits/test_rest_api_simpleflow.py, site/tests/legacy/test_communities.py, site/tests/legacy/test_quickstart.py, site/zenodo_rdm/api.py, site/zenodo_rdm/config.py, site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/legacy/ext.py, site/zenodo_rdm/legacy/resources.py, site/zenodo_rdm/legacy/serializers/__init__.py, site/zenodo_rdm/legacy/serializers/schemas.py, site/zenodo_rdm/legacy/serializers/schemas/__init__.py, site/zenodo_rdm/legacy/serializers/schemas/common.py, site/zenodo_rdm/legacy/serializers/schemas/files.py, site/zenodo_rdm/legacy/serializers/schemas/legacyjson.py, site/zenodo_rdm/legacy/serializers/schemas/zenodojson.py, site/zenodo_rdm/legacy/services.py, site/zenodo_rdm/legacy/views.py, site/zenodo_rdm/redirector.py, site/zenodo_rdm/tokens.py
=> Legacy REST API compatibility fixes

site/zenodo_rdm/custom_fields.py
closes https://github.com/zenodo/rdm-project/issues/224
=> custom fields: disabled software fields.

invenio.cfg
closes https://github.com/zenodo/rdm-project/issues/28
=> config: updated community record search.

invenio.cfg
closes https://github.com/zenodo/rdm-project/issues/249
=> config: added default publisher for records.

invenio.cfg
closes https://github.com/zenodo/rdm-project/issues/247
=> files: set default quota to 50gb

templates/semantic-ui/invenio_communities/frontpage.html
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/180
=> community frontpage: add aria label to search input

invenio.cfg, site/zenodo_rdm/facets.py
Closes https://github.com/zenodo/zenodo-rdm/issues/413, 
needs https://github.com/inveniosoftware/invenio-vocabularies/pull/268 - reason for failing tests
=> facets: add community facets

Pipfile.lock, site/tests/legacy/deposits/conftest.py, site/tests/legacy/deposits/test_rest_api_metadata.py, site/zenodo_rdm/legacy/deserializers/metadata.py, site/zenodo_rdm/legacy/serializers/schemas/common.py, site/zenodo_rdm/legacy/serializers/schemas/legacyjson.py
- Depends on https://github.com/inveniosoftware/invenio-rdm-records/pull/1478
=> legacy: fix alternate identifiers

site/zenodo_rdm/legacy/resources.py
closes https://github.com/zenodo/rdm-project/issues/258
=> zenodo: add etag headers to legacy API

site/zenodo_rdm/legacy/serializers/schemas/legacyjson.py
closes https://github.com/zenodo/zenodo-rdm/issues/531
=> legacy: fix communities records REST API response

site/zenodo_rdm/permissions.py
* closes https://github.com/zenodo/zenodo-rdm/issues/545
=> communities: disabled rename of communities

assets/less/zenodo-rdm/globals/site.variables
Partially Closes Issue [#365]([Invitation request page needs accessibility changes#365](https://github.com/inveniosoftware/invenio-requests/issues/365))
=> Fix: resolved text color contrast issue of comments

site/zenodo_rdm/sitemap/generators.py
- Updated to queries to use specific fields from the models.
- Remove search URL from sitemaps since there's no community specific search URL in RDM.
=> sitemap: generators: use specific fields in queries + remove search url

site/zenodo_rdm/metrics/views.py
This PR aims to complete and improve the metrics module
=> metrics: evaluation & result improvements

invenio.cfg
closes https://github.com/zenodo/zenodo-rdm/issues/524
=> configs: cleanup invenio.cfg

site/zenodo_rdm/legacy/serializers/schemas/common.py
* closes #539
Requires: https://github.com/inveniosoftware/invenio-communities/pull/1036
=> communities: use cached slug

site/zenodo_rdm/metrics/utils.py
Fixes #554 
We heard back from Marek that there's no good value we can return for Promtheus, so we are omitting the metric itself and logging an exception so we can keep track through sentry.
=> metrics: omit metric and log exception on failure

templates/semantic-ui/zenodo_rdm/records/detail.html
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1479
=> details: add deleted param to files previewer

site/zenodo_rdm/metrics/utils.py
=> metrics: evaluate metric before saving in result

invenio.cfg
Related to https://github.com/zenodo/rdm-project/issues/187
=> config: Update subject title for welcome email

templates/semantic-ui/zenodo_rdm/records/detail.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2464
=> landing page files: a11y and styling update for access-status cases

invenio.cfg
Fixes https://github.com/zenodo/rdm-project/issues/266
Added most viewed option to record search and record search in community.
=> search: add most viewed option to record search

invenio.cfg
closes https://github.com/zenodo/rdm-project/issues/223
=> config: added twitter handle

Dockerfile, invenio.cfg, krb5.conf, site/zenodo_rdm/files.py
Requires: https://gitlab.cern.ch/zenodo/zenodo-rdm-openshift/-/merge_requests/19
=> files: offload download

templates/semantic-ui/zenodo_rdm/footer.html
fixes https://github.com/zenodo/rdm-project/issues/304
=> footer: fix broken status link

site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/SupportForm.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/support.js, site/zenodo_rdm/templates/semantic-ui/zenodo_rdm/support.html, templates/semantic-ui/zenodo_rdm/footer.html
closes https://github.com/zenodo/rdm-project/issues/334
- Added "loading" state to the form so the button is blocked until the request is sent / fails
- Fixed an issue where users without full name would break the form
=> support: multiple fixes to support form.

invenio.cfg, templates/semantic-ui/invenio_accounts/register_user.html
closes https://github.com/zenodo/rdm-project/issues/330
=> oauth: temporarily removed openaire

invenio.cfg
closes https://github.com/zenodo/rdm-project/issues/331
=> config: fix orcid access token url.

site/zenodo_rdm/files.py
Guys, could we get this in first thing on the next release? 
I would like to make this exception a bit less vague https://zenodo-sentry.web.cern.ch/sentry/zenodo-rdm/issues/29446800/?query=is%3Aunresolved%20release%3A2.3.5
=> files: better exception visibility

site/zenodo_rdm/openaire/tasks.py
Context: executed the `retry` task and as soon as one record failed, all the others weren't retried. This could cause an indefinite blocking for the other records.
=> openaire: retries doesnt stop at the first exception.

site/zenodo_rdm/config.py, site/zenodo_rdm/views.py
=> frontpage: change recent uploads query

invenio.cfg
closes https://github.com/zenodo/rdm-project/issues/377
Values taken from legacy. There are other values there, for now, I am not touching those.
=> config: bump badges rate limits.

invenio.cfg, site/zenodo_rdm/files.py
closes https://github.com/zenodo/rdm-project/issues/376
=> search: added conceptrecid paremeter translation.

invenio.cfg
Closes https://github.com/zenodo/rdm-project/issues/390
=> search: update default sort options

invenio.cfg, site/zenodo_rdm/github/release.py, site/zenodo_rdm/github/schemas.py
closes https://github.com/zenodo/zenodo-rdm/issues/407
=> github: added zenodo specific release metadata.

site/zenodo_rdm/config.py, site/zenodo_rdm/permissions.py
* closes https://github.com/zenodo/rdm-project/issues/398
=> permissions: modify record files as admin

site/zenodo_rdm/github/release.py
closes https://github.com/zenodo/rdm-project/issues/434
=> github: added default repo creators.

templates/semantic-ui/invenio_communities/frontpage.html, templates/semantic-ui/zenodo_rdm/frontpage.html, templates/semantic-ui/zenodo_rdm/macros/carousel_item.html, templates/semantic-ui/zenodo_rdm/macros/communities_carousel_slides.html, templates/semantic-ui/zenodo_rdm/macros/featured_communities_carousel.html
=> featured: make new upload btn optional

templates/security/email/welcome.html
=> email: updated welcome email template

invenio.cfg, site/zenodo_rdm/legacy/deserializers/metadata.py, site/zenodo_rdm/legacy/resources.py, site/zenodo_rdm/legacy/serializers/schemas/zenodojson.py, site/zenodo_rdm/legacy/services.py
closes https://github.com/zenodo/rdm-project/issues/453
closes https://github.com/zenodo/rdm-project/issues/465
=> Legacy api upload worflow

site/zenodo_rdm/github/release.py
closes https://github.com/zenodo/rdm-project/issues/427
=> github: fixed error messages for metadata loading.

site/zenodo_rdm/files.py
* fix attachment download flag
* closes https://github.com/zenodo/rdm-project/issues/401
=> files: normalize headers encoding

templates/semantic-ui/zenodo_rdm/macros/carousel_item.html
* closes https://github.com/zenodo/rdm-project/issues/433
=> community logo: fix rendering placeholder

site/zenodo_rdm/files.py
* closes https://github.com/zenodo/rdm-project/issues/488
=> files: set urlecaped filename content disposition

site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/openaire/tasks.py
- tasks: log OpenAIRE indexing exceptions
- legacy: fix PIDs loading
=> Legacy REST API fixes and OpenAIRE indexing logging

legacy/zenodo_legacy/data/legacy_to_rdm_map.json
closes https://github.com/zenodo/rdm-project/issues/529
=> legacy: added missing license alias.

templates/semantic-ui/zenodo_rdm/records/detail.html, templates/semantic-ui/zenodo_rdm/records/details/details.html, templates/semantic-ui/zenodo_rdm/records/macros.html
Closes https://github.com/zenodo/rdm-project/issues/446
Needs: https://github.com/inveniosoftware/invenio-app-rdm/pull/2520 << Screenshots and explanation
=> landing page: Add legacy subjects to additional details

site/tests/conftest.py, site/zenodo_rdm/legacy/deserializers/metadata.py, site/zenodo_rdm/legacy/serializers/schemas/common.py
Fixes https://github.com/zenodo/rdm-project/issues/516
=> legacy: fix notes in metadata

site/zenodo_rdm/config.py
* closes https://github.com/zenodo/rdm-project/issues/548
=> config: add mathjax support

Pipfile.lock, site/zenodo_rdm/legacy/serializers/schemas/common.py
- Closes https://github.com/zenodo/rdm-project/issues/582
- legacy: fix contributor roles mapping
- installation: update Pipfile.lock
=> Fix contributor roles mappings and update deps

site/zenodo_rdm/permissions.py
* closes https://github.com/zenodo/rdm-project/issues/482
* NEEDS https://github.com/inveniosoftware/invenio-rdm-records/pull/1605
=> permissions: update permissions

site/zenodo_rdm/legacy/serializers/schemas/common.py
* closes https://github.com/zenodo/rdm-project/issues/558
=> serializers: change dates field format to EDTFDateAndTime

templates/semantic-ui/zenodo_rdm/frontpage.html
Closes https://github.com/zenodo/rdm-project/issues/586
=> frontpage: add newsletter box

templates/semantic-ui/invenio_communities/frontpage.html
Fix for the breaking changes in https://github.com/inveniosoftware/invenio-communities/pull/1071
Specifically: https://github.com/inveniosoftware/invenio-communities/pull/1071/files#r1409494329
=> templates: communities: fix div id

assets/less/zenodo-rdm/globals/site.overrides, site/zenodo_rdm/config.py, templates/semantic-ui/invenio_app_rdm/site_footer.html, templates/semantic-ui/zenodo_rdm/footer.html, templates/themes/horizon/invenio_app_rdm/footer.html, templates/themes/horizon/invenio_communities/details/header.html
closes https://github.com/zenodo/horizon-zen/issues/46
=> templates: split footer template

site/zenodo_rdm/legacy/serializers/__init__.py
Closes Issue https://github.com/zenodo/rdm-project/issues/426
=> schema: updated json serializer list schema

site/zenodo_rdm/legacy/serializers/schemas/legacyjson.py
Closes Issue [#639](https://github.com/zenodo/rdm-project/issues/639)
=> files: fix pending files keyError in legacyjson

Pipfile.lock, site/zenodo_rdm/config.py, site/zenodo_rdm/redirector.py, templates/themes/horizon/invenio_app_rdm/footer.html, templates/themes/horizon/invenio_communities/details/header.html, templates/themes/horizon/invenio_communities/details/home/index.html
Closes Issue #689 
P.s only review my commit
=> horizon: update header, footer and redirection

invenio.cfg
Closes https://github.com/zenodo/ops/issues/350
=> config: fix orcid/openaire sandbox endpoints

invenio.cfg
closes https://github.com/zenodo/ops/issues/309
=> config: added sort by created to sort by pubdate.

app_data/pages.yaml, templates/themes/horizon/invenio_app_rdm/default_static_page.html
Closes Issue [#706](https://github.com/zenodo/zenodo-rdm/issues/706)
=> pages: added horizon static page

app_data/pages.yaml
Closes Issue [#706](https://github.com/zenodo/zenodo-rdm/issues/706)
=> static_pages: updated url for pages

invenio.cfg
closes https://github.com/zenodo/ops/issues/315
=> config: added funders datacite priority.

app_data/vocabularies.yaml, app_data/vocabularies/euroscivoc.jsonl
closes https://github.com/zenodo/zenodo-rdm/issues/732
=> vocabularies: added European Science Vocbulary

Pipfile.lock, templates/themes/horizon/invenio_communities/details/home/index.html
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/747
=> frontpage: added browse section for metrics

scripts/ec_transfer_records.py
leftover from the rename done in https://github.com/inveniosoftware/invenio-rdm-records/issues/1677
=> scripts: fixed bulk parent update call.

app_data/pages.yaml, app_data/pages/horizon/how-to-submit.html, templates/semantic-ui/invenio_communities/community_theme_template.css, templates/themes/horizon/invenio_app_rdm/default_static_page.html
Fixes #761 
This is the "How to Submit" page.
=>  Static page: How to submit

app_data/pages.yaml, app_data/pages/horizon/join.html
Fixes https://github.com/zenodo/zenodo-rdm/issues/761
=>  Static page: Join

templates/semantic-ui/zenodo_rdm/footer.html
Closes Issue https://github.com/zenodo/ops/issues/369
=> footer: updated github link

app_data/pages/horizon/how-to-submit.html, app_data/pages/horizon/join.html, templates/semantic-ui/invenio_communities/community_theme_template.css
Fixes #761
The Sandbox versions:
* [How to Submit (Sandbox)](https://sandbox.zenodo.org/communities/eu/pages/how-to-submit)
* [Join (Sandbox)](https://sandbox.zenodo.org/communities/eu/pages/join)
The versions with fixed responsiveness:
* [How to Submit (this PR)](https://ptamarit.web.cern.ch/temp/zenodo-rdm-761/how-to-submit.html)
* [Join (this PR)](https://ptamarit.web.cern.ch/temp/zenodo-rdm-761/join.html)
=> Static pages: horizon-zen latest changes & fix grid layout responsiveness

scripts/deploy.py, site/zenodo_rdm/openaire/serializers/schema.py
- **scripts: allow filtering deployments**
- **openaire: fix license serialization**
=> OpenAIRE direct indexing license fix

invenio.cfg
closes https://github.com/zenodo/ops/issues/340
* Added missing facet, needed for administration drafts
=> config: added is_published to the search facets

site/zenodo_rdm/legacy/services.py
Closes https://github.com/zenodo/ops/issues/348
=> files: fixed download links

site/zenodo_rdm/metrics/api.py
Close https://github.com/zenodo/ops/issues/392
Error: 
```bash
[2024-03-20 16:12:19,477: ERROR/ForkPoolWorker-17] Metric evaluation failed
Traceback (most recent call last):
File "/Users/cmackenz/git/zenodo-rdm/site/zenodo_rdm/metrics/utils.py", line 29, in calculate_metrics
metric["value"] = metric["value"]()
File "/Users/cmackenz/git/zenodo-rdm/site/zenodo_rdm/metrics/api.py", line 107, in get_uptime
for d in res.json()["monitors"]
KeyError: 'monitors'
```
The key is not found as when run locally the API returns:
```json
{"stat": "fail", "error": {"type": "missing_parameter", "parameter_name": "api_key", "message": "api_key parameter is missing."}}
```
Also `datetime.utcnow()` is deprecated so I have exchanged it for the correct implementation …
=> bug: don't call uptime robot when no API key passed

templates/semantic-ui/zenodo_rdm/trackingcode/trackingcode-prod.html, templates/semantic-ui/zenodo_rdm/trackingcode/trackingcode-qa.html
Close https://github.com/zenodo/ops/issues/404
Misunderstood domain vs path, as the values should be same everywhere, equivalent pull request https://github.com/zenodo/zenodo-docs-user/pull/120
=> bug: fix cookie behaviour across subdomains

invenio.cfg
Closes Issue https://github.com/zenodo/ops/issues/406
=> config: added limit for reset password endpoints

site/zenodo_rdm/permissions.py
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1671
=> permissions: add grant "manage" permission

Pipfile, Pipfile.lock, assets/js/invenio_app_rdm/overridableRegistry/mapping.js, invenio.cfg, scripts/ec_transfer_records.py, site/zenodo_rdm/legacy/serializers/schemas/legacyjson.py
- **scripts: fix bulk community record transfer**
- **assets: fix formatting**
- **config: remove duplicate frontpage view override**
=> Minor fixes and release

app_data/pages.yaml, scripts/ec_transfer_records.py
- **pages: remove `has_custom_view` column**
- **scripts: fix EC transfer records parameter**
=> Fix EC script and page fixtures

site/zenodo_rdm/legacy/deserializers/metadata.py
255 associated events, ZENODO-RDM-1WN
=> bug: check legacy_license is defined

docker-compose.yml, docker-services.yml, invenio.cfg
* added iipserver service to docker-compose.yml
* enabled IIPServerProxy in invenio.cfg
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1728
=> docker: added iipserver service

assets/less/zenodo-rdm/globals/site.overrides, invenio.cfg, site/MANIFEST.in, site/zenodo_rdm/assets/semantic-ui/less/zenodo_rdm/previewer/mirador-previewer.less, site/zenodo_rdm/previewer/mirador.py, site/zenodo_rdm/webpack.py, templates/semantic-ui/invenio_app_rdm/records/mirador_preview.html, templates/semantic-ui/zenodo_rdm/records/detail.html
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/819
Partially Closes https://github.com/zenodo/zenodo-rdm/issues/840
Depends on: https://github.com/inveniosoftware/invenio-app-rdm/pull/2652
Depends on: https://github.com/inveniosoftware/invenio-app-rdm/pull/2657
=> previewer: added mirador previewer

invenio.cfg
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1672
=> config: rename groups enabled feature flag

README.md
=> Make README logo dynamic with theme

Pipfile.lock
- picking up new minor for `invenio-jobs`
=> installation: bump dependencies

app_data/pages/horizon/join.html
Close https://github.com/inveniosoftware/invenio-communities/issues/1150
=> static_page: change join waiting list to join community

invenio.cfg, site/zenodo_rdm/subcommunities/__init__.py, site/zenodo_rdm/subcommunities/request.py, site/zenodo_rdm/subcommunities/schema.py
=> subcommunities: added  request type in  Zenodo

assets/js/components/community/SearchDropdown.js, assets/js/components/community/overrides/SubcommunityCreateForm.js, assets/js/invenio_app_rdm/overridableRegistry/mapping.js
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/890
~~depends on: https://github.com/inveniosoftware/react-invenio-forms/pull/243~~
=> communities:override subcommunity form for project

assets/js/components/community/SearchDropdown.js, assets/js/components/community/overrides/SubcommunityCreateForm.js
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/909
- **Added autofill**: Closes Issue https://github.com/zenodo/zenodo-rdm/issues/903
- **Updated text**: Closes Issue https://github.com/zenodo/zenodo-rdm/issues/909
- **Minor code updates**:  Closes Issue https://github.com/zenodo/zenodo-rdm/issues/912
=> Subcommunity:added autofill and text updates

app_data/communities.yaml, app_data/img/horizon-zen.png, app_data/users.yaml, site/zenodo_rdm/subcommunities/request.py
=> subcommunities: add sytem comment on create request

Pipfile, Pipfile.lock, invenio.cfg, site/zenodo_rdm/permissions.py
- **config: clean-up unused imports and duplicates**
- **permissions: fix draft media-files list permission**
=> Annotations fixes and bump deps

invenio.cfg
- Closes https://github.com/zenodo/zenodo-rdm/issues/939
=> config: add user moderation tasks to "spam" queue

invenio.cfg, site/tests/requests/test_community_manage_record_request.py, site/tests/requests/test_record_upgrade_request.py, site/tests/resources/test_record_file_permissions.py, site/zenodo_rdm/custom_fields/publishing.py, site/zenodo_rdm/files.py, site/zenodo_rdm/legacy/deserializers/metadata.py, site/zenodo_rdm/legacy/requests/community_manage_record.py, site/zenodo_rdm/legacy/requests/record_upgrade.py, site/zenodo_rdm/openaire/utils.py, site/zenodo_rdm/params.py, site/zenodo_rdm/partners/payloads.py, site/zenodo_rdm/partners/plazi.py, site/zenodo_rdm/redirector.py, site/zenodo_rdm/sitemap/generators.py, site/zenodo_rdm/stats/ext.py, site/zenodo_rdm/support/support.py, site/zenodo_rdm/utils.py, templates/semantic-ui/zenodo_rdm/records/detail.html
=> records-ui: add meta robots tags

templates/semantic-ui/invenio_app_rdm/records/macros/files.html
- The link associated with annotate button to open in new tab window
=> annotation: annotate link to open in new tab

.github/workflows/tests.yml, invenio.cfg, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/citations/CitationsSearch.js
- **ci: update workflow config and split JS from Python tests**
- **config: set 50GB bucket quota via old config**
- **records-ui: update link to citations FAQ**
=> Various small fixes

assets/js/components/landing_page/overrides/UpgradeLegacyRecordButton.js
* closes https://github.com/zenodo/rdm-project/issues/598
=> http headers: use and adjust vnd.inveniordm.v1+json http accept header

invenio.cfg, site/zenodo_rdm/files.py
Closes Issue: https://github.com/zenodo/ops/issues/402
=> config: enabled file-integrity checks

docker/nginx/conf.d/default.conf
=> nginx: add rate-limiting for crawlers

invenio.cfg
=> config: add subcommunity facets

invenio.cfg, site/zenodo_rdm/previewer/image_previewer.py
- Refactor and adds checks for pdfs being previewed by the image_previewer
=> previewer: fix for viewing pdf in mirador

app_data/pages/horizon/how-to-submit.html, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/horizon/community-item.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/horizon/index.js, site/zenodo_rdm/webpack.py, templates/themes/horizon/invenio_communities/details/home/index.html
Closes Issue: https://github.com/inveniosoftware/invenio-communities/issues/1227
Depends on: https://github.com/inveniosoftware/invenio-rdm-records/pull/1845
**Added Browse Collections Area**
**Changed Submit Directly button to text link**
=> Eu frontpage

Pipfile.lock
📁 invenio-app-rdm (13.0.0b1.dev13 -> 13.0.0b1.dev14 )
📦 release: v13.0.0b1.dev14
communities-ui: make verified icon display depend on parent community
📁 invenio-communities (17.3.0 -> 17.3.1 🐛)
📦 release: v17.3.1
communities-ui: make verified icon display depend on parent community
📁 invenio-rdm-records (15.4.0 -> 15.5.0 🌈)
📦 release: v15.5.0
community: added autofocus prop to CommunitySelectionSearch
=> installation: bump dependencies (v12.3.2)

invenio.cfg
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1852
=> Add collections task

site/zenodo_rdm/moderation/config.py, site/zenodo_rdm/moderation/rules.py
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/1044
=> moderation: added rule for excessive header tags

site/setup.cfg, site/zenodo_rdm/cli.py, site/zenodo_rdm/moderation/config.py, site/zenodo_rdm/moderation/handlers.py, site/zenodo_rdm/moderation/models.py, site/zenodo_rdm/moderation/percolator.py, site/zenodo_rdm/moderation/rules.py, site/zenodo_rdm/moderation/tasks.py, site/zenodo_rdm/moderation/uow.py
- Closes #1046.
- **moderation: update workflow for exempt and verified users**
- **moderation: fix percolators index naming and CLI usage**
=> Moderation fixes

site/zenodo_rdm/github/release.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1887
=> github: add default license from Github API

invenio.cfg, site/zenodo_rdm/moderation/config.py, site/zenodo_rdm/moderation/handlers.py, site/zenodo_rdm/moderation/tasks.py
Refactor to accommodate ML model results and better logging.
=> moderation: add rule results to dict and eval

site/zenodo_rdm/subcommunities/request.py
=> fix: typo and link in invitation

site/zenodo_rdm/curation/jobs.py, site/zenodo_rdm/curation/tasks.py
=> curation: use utcnow

templates/themes/biosyslit/invenio_communities/details/home/index.html, templates/themes/nih/invenio_communities/details/home/index.html
- Updated BiodiversityPMC instance link
- Updated class for links
=> UI: url and class updates in branded communities

Pipfile, Pipfile.lock, site/zenodo_rdm/custom_fields/__init__.py, site/zenodo_rdm/custom_fields/publishing.py, site/zenodo_rdm/legacy/deserializers/schemas.py
Closes Issue https://github.com/zenodo/zenodo-rdm/issues/1169
=> custom_fields: added old thesis field for migration

invenio.cfg, site/zenodo_rdm/custom_fields/__init__.py, site/zenodo_rdm/custom_fields/publishing.py, site/zenodo_rdm/legacy/deserializers/schemas.py, site/zenodo_rdm/legacy/serializers/schemas/legacyjson.py
Closes Issue https://github.com/zenodo/ops/issues/519
=> custom-fields: revert thesis migration changes

invenio.cfg
1. Creating indexing queue to reduce load on the default queue
2. Add all clean up tasks to low queue
=> celery: create indexing queue and add more tasks to low

site/zenodo_rdm/templates/semantic-ui/invenio_checks/requests/help_message.html
Closes https://github.com/inveniosoftware/invenio-checks/issues/27
=> checks: create help msg override

Pipfile.lock, app_data/vocabularies.yaml, app_data/vocabularies/awards.yaml, app_data/vocabularies/funders.yaml
- **fixtures: add funders and awards**
📁 invenio-checks (0.3.0 -> 0.3.1 🐛)
📦 release: v0.3.1
requests-ui: handle multiple check runs of same type
* Handles rendering of multiple check run results for the metadata
check type.
* Uses the first instance of file format checks.
📁 invenio-i18n (3.0.0 -> 3.1.0 🌈)
release: v3.1.0
📁 invenio-jobs (3.1.1 -> 3.2.0 🌈)
release: v3.2.0
logging: add log deletion task
release: v3.1.2
logs: fix minor bug
=> fix checks request tab

scripts/export-all-xml.py, scripts/export-blr.py
Fixes #1164 
Since we will have to trigger these scripts monthly until it is fully automated, it does make sense to commit them to Git.
=> exporter: scripts

invenio.cfg
Shows a checklist in case of deletion request (not in case of immediate deletion).
This is introduced as a way to try to decrease support load.
Depends on:
* inveniosoftware/invenio-rdm-records#2153
* inveniosoftware/invenio-app-rdm#3183
=> deletion-request: checklist for request

site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/CategoryDropdown.js, site/zenodo_rdm/assets/semantic-ui/js/zenodo_rdm/src/support/components/SupportForm.js, site/zenodo_rdm/config.py, site/zenodo_rdm/support/views.py
- **support form: fix global error message for validation errors**
- **support form: show success message in React**
- **support form: disable the form for record deletion**
- **support form: show message category, subject and content**
=> support feedback
